### ISSUE TITLE
# TODO

### ISSUE THREAD

**Issue by n-masayoshi** [n-masayoshi/laravel_crud#7]
- [ ] データ登録の仕方
    - [ ] 国テーブル(m_country)を作成
        - [ ] 選手名(player_name), 年齢(age), 所属チーム(club_team_name)カラムの作成
- [ ] データ取得・表示
- [ ] 国一覧ページの作成
- [ ] クラブチーム一覧ページの作成

**Comment by n-masayoshi** [comment]
# テーブル一覧
#### 国：m_country
| 国 | m_country |  |  |
| ---- | ---- | ---- | ---- |
| country_id | int | key |  |
| country_name | string | char(50) | NOT NULL |

#### 各国の選手一覧：m_<country>_players
| 選手一覧 | m_<country>_players |  |  |
| ---- | ---- | ---- | ---- |
| club_team_id | int | FKey | NOT NULL |
| player_name | string | NOT NULL | |
| player_age | int | NOT NULL | |

**Comment by n-masayoshi** [comment]
## 日本人選手一覧ページ
- [ ] 選手表示
- [ ] 選手登録
- [ ] 国一覧ページからの遷移
  - [ ] `views/Country/index`から、`Controllers/Players/JapanesePlayersController`に、`country_id`を渡す
  - [ ] その `id` をもとに、日本人選手一覧ページを表示するロジックにする。

**Comment by n-masayoshi** [comment]
### プレミアリーグテーブル作成
- [ ] 例えば、2010年から「優勝チーム（club_team_id）」「最多ゴール選手（most_goal_player_name）」「最多アシスト選手（most_assist_player_name）」のカラムを作成
